apiVersion: v1
appVersion: "0.1.0"
description: A Helm chart for reumanager
name: reumanager
version: 0.1.0
dependencies:



  - name: postgresql
    version: 10.3.18
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

