stages:
- build
- test
- deploy

before_script:
- export TAG=${CI_COMMIT_SHORT_SHA}
- export BRANCH=${CI_COMMIT_REF_SLUG}
- export REGISTRY_HOST=${CI_REGISTRY}
- export REGISTRY_URI="/${CI_PROJECT_PATH}"

build:
  stage: build
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_JOB_TOKEN" $CI_REGISTRY
    - sc build
    - sc push
    - docker tag $CI_REGISTRY_IMAGE:$TAG $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - local

test:
  stage: test
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  services:
        - name: postgres:11.1
  variables:
    DATABASE_ADAPTER: postgresql
    DATABASE_HOST: postgres
    DATABASE_NAME: reumanager
    DATABASE_PASSWORD: password
    DATABASE_USER: postgres
    GIT_STRATEGY: none
    POSTGRES_DB: reumanager
    POSTGRES_HOST: postgres
    POSTGRES_PASSWORD: password
    POSTGRES_USER: postgres
    SITE_URI_BASE: TODO
    TEST_DB: reumanager
  script:
    - ls -l
    - cd /app && rails db:create db:schema:load
    - cd /app && rspec
  tags:
    - docker

staging:
  stage: deploy
  type: deploy
  script:
  - ./chart/bin/deploy staging $CI_COMMIT_REF_SLUG $STAGING_CONFIG_FILE
  when: manual
  tags:
    - local

production:
  stage: deploy
  type: deploy
  script:
  - ./chart/bin/deploy production $CI_COMMIT_REF_SLUG $STAGING_CONFIG_FILE
  when: manual
  tags:
    - local
