version: '2.1'
services:
  postgres:
    image: postgres
    env_file:
      - .env
      - .env.development
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
  web:
    build: .
    image: "${REGISTRY_HOST}${REGISTRY_URI}:${TAG:-master}"
    volumes:
      - .:/home/app/webapp
    env_file:
      - .env
      - .env.development

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true
    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
    ports:
      - "5555:80"
    depends_on:
      - postgres

volumes:
  postgres:
