# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4a1479c1b49fb7070afbd264fec1a068a5371503031b8f732056fafdde0f61ced041804802aa4a98c3bb0bab62ccfd88ba5c183f78c595b8a163a77ab4c11c21
  stripe_secret_key: <%= ENV["STRIPE_SECRET_TOKEN"] || 'sk_test_xp6wrmUz73aXUdQb7XDZm7mt' %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_TOKEN"] ||'pk_test_p7UXZiQWomIICnrBTZna13sH' %>

test:
  secret_key_base: f410258967f961489a93ab8b02a26a08d938375465e83777d150e2ec8f3b2e5f4ef6434db6c8d5e458c2dcd175cf90b0426e6503e2dd01e6053edc361a83dac0
  stripe_secret_key: <%= ENV["STRIPE_SECRET_TOKEN"] || 'sk_test_xp6wrmUz73aXUdQb7XDZm7mt' %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_TOKEN"] ||'pk_test_p7UXZiQWomIICnrBTZna13sH' %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_secret_key: <%= ENV["STRIPE_SECRET_TOKEN"] || 'sk_test_xp6wrmUz73aXUdQb7XDZm7mt' %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_TOKEN"] ||'pk_test_p7UXZiQWomIICnrBTZna13sH' %>

